name:                Hascss
version:             0.1.0.0
github:              "anthonysuper/Hascss"
license:             BSD3
author:              "Anthony Super"
maintainer:          "anthony@noided.media"
copyright:           "2018 Anthony Super"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AnthonySuper/Hascss#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- hashable
- hspec

library:
  source-dirs: src

executables:
  Hascss-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hascss

tests:
  Hascss-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hascss
    - hspec == 2.*
